# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pismo
      MYSQL_DATABASE: pismo
    ports:
      - "3306:3306"
    volumes:
        - /C/dev/docker/mysql/mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080